### ISSUE TITLE
repo description is a bit misleading

### ISSUE THREAD

**Issue by StephenHodgson** [Blockade-Games/BlockadeLabs-SDK-Unity#2]
https://github.com/Blockade-Games/BlockadeLabs-SDK-Unity/blob/6d0e81513134973b5951aa640ac0b7517e22cd0f/README.md?plain=1#L3

**Comment by GoranPopovic1** [comment]
Any part in particular do you find misleading? Any suggestion to improve it?

How about:

"Create stunning AI-generated skybox assets within Unity for use as HDRIs in game dev and immersive projects."

We will probably use that one for the asset store package.

**Comment by GoranPopovic1** [comment]
This was updated: https://github.com/Blockade-Games/BlockadeLabs-SDK-Unity#blockade-labs-sdk-for-unity
