### ISSUE TITLE
Create Skybox Error: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by justinduynguyen** [Blockade-Games/BlockadeLabs-SDK-Unity#5]
I filled API key that i just purchased but it's raised this error when i click on Initialize

**Comment by GoranPopovic1** [comment]
@justinduynguyen Try to close the project completely and then reopen it again. Add the key again and click on Initialize. Make sure that you are using the public API key, not the secret one. It's also possible that we were under heavy load at that point, or that the service was temporarily down so please try again in any case.

If the issue persists, please provide any additional details you are able. Which Unity version are you using? Any screenshots and logs from the Unity console might help as well. Also, please send me an email you used when requesting your API key, I would like to try to reproduce the issue using your API key.
