### ISSUE TITLE
Download glb from API

### ISSUE THREAD

**Issue by yosun** [Blockade-Games/BlockadeLabs-SDK-Unity#9]
Is there a way to download .glb from the API?

**Comment by yosun** [comment]
Hence why it's a feature request? The web app generates .glb so I assume the server is already setup to generate the .glb ... just expose the API

**Comment by yosun** [comment]
Major issue is that the depth mask shader does not work for visionos's strict URP - but I have been able to load .glb at runtime https://github.com/Blockade-Games/BlockadeLabs-SDK-Unity/issues/8

**Comment by StephenHodgson** [comment]
> Hence why it's a feature request? The web app generates .glb so I assume the server is already setup to generate the .glb ... just expose the API

No API needed. Mesh generation is done in the unity package directly.

**Comment by yosun** [comment]
ah only quickly tested on visionos - 

is that editor only or runtime as well? 

if mesh is generated what's with the depth masks? Shader 'BlockadeLabsSDK/BlockadeSkyboxDepth etc

**Comment by StephenHodgson** [comment]
> is that editor only or runtime as well?

Yes you should be able to request a skybox at runtime and it generate the mesh for you.
Unfortunately I think it is going to use the shader that breaks for visionOS. I believe a fix is in progress for #8

**Comment by StephenHodgson** [comment]
@yosun btw if in editor you can save the mesh as a prefab and apply your own shader/materials to it that are compatible with visionOS in the meantime while we work on that fix

**Comment by yosun** [comment]
or just request that they add a .glb to their API endpoint

**Comment by yosun** [comment]
hey! is glb added ?

**Comment by StephenHodgson** [comment]
there is no glb. We reconstruct the mesh from the image dynamically, and yes this feature has been available for some time.
